saving_box:
    resource: "@SavingBoxBundle/Controller/"
    type:     annotation
    prefix:   /savings
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /admin
    
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
portada:
    pattern:  /{_locale}
    defaults: { _controller: SavingBoxBundle:Default:index, _locale: es }
    requirements:
        _locale: en|es

# Ruta de la portada básica del sitio (sin ningún parámetro)
# esta ruta es opcional, ya que la aplicación puede funcionar bien
# solamente con la ruta 'portada' y sus valores por defecto
_portada:
     pattern:  /
     defaults: { _controller: FrameworkBundle:Redirect:redirect, route: portada, permanent: true }