Prestamo:
    type: entity
    table: prestamo
    indexes:
        fk_prestamo_1_idx:
            columns:
                - persona_id
        fk_prestamo_data_idx:
            columns:
                - data_id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipoPrestamoId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: tipo_prestamo_id
        nSolicitud:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: n_solicitud
        nCuotas:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: n_cuotas
        porcentajeInteres:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: porcentaje_interes
        prestamoAnterior:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: prestamo_anterior
        montoCheque:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: monto_cheque
        gastosAdministrativos:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: gastos_administrativos
        tipoPago:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: tipo_pago
        fechaSolicitud:
            type: datetime
            nullable: false
            comment: ''
            column: fecha_solicitud
        montoSolicitud:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: monto_solicitud
        montoCuota:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: monto_cuota
        montoInteres:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: monto_interes
        reintegroInteres:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: reintegro_interes
        totalPrestamo:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: total_prestamo
        usuarioId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: usuario_id
        ip:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
        updatedAt:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: updated_at
    manyToOne:
        persona:
            targetEntity: Persona
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                persona_id:
                    referencedColumnName: id
            orphanRemoval: false
        data:
            targetEntity: Data
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
          prePersist: [ setCreatedAtValue ]
          preUpdate: [ setUpdatedAtValue ]
