Persona:
    type: entity
    table: persona
    indexes:
        IDX_51E5B69BCC04A73E:
            columns:
                - banco_id
        IDX_51E5B69B37F5A13C:
            columns:
                - data_id
    uniqueConstraints:
        ci_UNIQUE:
            columns:
                - ci
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ci:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        nombre1:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: nombre_1
        nombre2:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: nombre_2
        apellido1:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: apellido_1
        apellido2:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: apellido_2
        fechaNac:
            type: date
            nullable: false
            comment: ''
            column: fecha_nac
        sexo:
            type: string
            nullable: false
            length: 1
            fixed: false
            comment: ''
        img:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        tlfMovil:
            type: decimal
            nullable: true
            precision: 11
            scale: 0
            comment: ''
            column: tlf_movil
        tlfFijo:
            type: decimal
            nullable: true
            precision: 11
            scale: 0
            comment: ''
            column: tlf_fijo
        email:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        facebookId:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: facebook_id
        twitterId:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: twitter_id
        direccion:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        nCuenta:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: n_cuenta
        tCuenta:
            type: string
            nullable: true
            length: 1
            fixed: false
            comment: ''
            column: t_cuenta
        usuarioId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: usuario_id
        ip:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
    manyToOne:
        data:
            targetEntity: Data
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                data_id:
                    referencedColumnName: id
            orphanRemoval: false
        banco:
            targetEntity: Banco
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                banco_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
          prePersist: [ setCreatedAtValue ]
          preUpdate: [ setUpdatedAtValue ]