services:
  
    saving_box.admin.persona:
        class: Saving\BoxBundle\Admin\PersonaAdmin
        arguments: [~, Saving\BoxBundle\Entity\Persona, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Persona}

    saving_box.admin.data:
        class: Saving\BoxBundle\Admin\DataAdmin
        arguments: [~, Saving\BoxBundle\Entity\Data, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Data}

    saving_box.admin.banco:
        class: Saving\BoxBundle\Admin\BancoAdmin
        arguments: [~, Saving\BoxBundle\Entity\Banco, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Banco}

    saving_box.admin.prestamo:
        class: Saving\BoxBundle\Admin\PrestamoAdmin
        arguments: [~, Saving\BoxBundle\Entity\Prestamo, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Prestamo}
